var cityinfo = {
	
	// MAJOR CITIES
	
	"croakenford" : {
		"id" : 0,
		"type" : "Major",
		"coord" : [-60.15244, 27.59766],
		"name" : "Croakenford",
		"region" : "Shatterlands",
		"district" : "Sharden",
		"description" : "The harbor city of Croakenford is maybe the most important city since it is the main port for exports and exports in Esmorzar.",
		"majorpop" : "Human, Diverse",
		"features" : ["Grand Harbor", "Trade export market"],
		"vip" : [],
	},
	"eifelheim" : {
		"id" : 1,
		"type" : "Major",
		"coord" : [71.63599, 14.23828],
		"name" : "Eifelheim",
		"region" : "Leylands",
		"district" : "Mweiwar Wilds",
		"description" : "The central and capital Elven city in Esmorzar. Deep in to eh Mweiwar Wilds, it is a very defensible location protected by the surrounding Elfkin",
		"majorpop" : "Elven",
		"features" : [],
		"vip" : [],
	},
	"faolin" : {
		"id" : 2,
		"type" : "Major",
		"coord" : [63.62674, -73.125],
		"name" : "Faolin",
		"region" : "Crawling Kingdom",
		"district" : "Northern Crawl",
		"description" : "The Northern Crawl is a mountainous area of Ezmorzar, and in a clearing lies Faolin, a city known for its farmland",
		"majorpop" : "Human, Dwarven, Diverse",
		"features" : [],
		"vip" : [],
	},
	"tandent" : {
		"id" : 3,
		"type" : "Major",
		"coord" : [-33.28462, -125.50781],
		"name" : "Tandent",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The snout of Waverwen, Tandent is the capital of the Waverwen district. A large bustling city that maintains the whole regions trading and marketing.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"teitrasyl" : {
		"id" : 4,
		"type" : "Major",
		"coord" : [-12.72608, 92.98828],
		"name" : "Teitrasyl",
		"region" : "Endling",
		"district" : "Godsend",
		"description" : "The kingsland of Esmorzar, the home of the Pantheon, Teitrasyl holds some of the most historical and priceless monuments and features in Esmorzar.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"thragg" : {
		"id" : 5,
		"type" : "Major",
		"coord" : [-41.37681, -49.57031],
		"name" : "Thragg",
		"region" : "Shatterlands",
		"district" : "Craggy",
		"description" : "One of the 3 major Dwarven cities and sister city to Thrull, Thragg was a city made to exploit the great mineral harvests of the Craggy.",
		"majorpop" : "Dwarven",
		"features" : ["adssd"],
		"vip" : [],
	},
	"thrull" : {
		"id" : 6,
		"type" : "Major",
		"coord" : [51.17934, 119.70703],
		"name" : "Thrull",
		"region" : "Cape Drifting",
		"district" : "",
		"description" : "The sister city of Thragg, Thrull relies on its cold coast for the harvest and export for sustaining trade prominence",
		"majorpop" : "Dwarven",
		"features" : [],
		"vip" : [],
	},
	"waterhill" : {
		"id" : 7,
		"type" : "Major",
		"coord" : [47.39835, 51.67969],
		"name" : "Waterhill",
		"region" : "Endling",
		"district" : "Dweiwar",
		"description" : "An outpost village turned into a trade center, sitting at the crossroads between major cities it serves as a hub between them. It fills an identical job to Rocton, a smaller city. This village relies on farmland and lumber harvest for economy.",
		"majorpop" : "Elven, Dwarven, Diverse",
		"features" : [],
		"vip" : [],
	},
	
// ## Minor Cities & Features sorted by region 

	// CRAWLING KINGDOM
	
		//Waverwen
	
	"turning" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Turning Outpost Village",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The outpost township of turning is one of the major villages that acts as guards to the gates of Waverwen",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"lugia" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Lugia",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "Most of the the treasuring Waverwen holds is transported here.",
		"majorpop" : "",
		"features" : ["Main Bank of Waverwen"],
		"vip" : [],
	},
	"waverlycoast" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Waverly Coast Township",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The harbor village of Waverly Coast is important for the economy of Waverwen as this township delivers most of the food resources, catching game from nearly areas and using the nearby waters for fishing.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"coaltown" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Coaltown",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The outpost township of turning is one of the major villages that acts as guards to the gates of Waverwen",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
		// Yiva
	
	"trasten" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Trasten Town",
		"region" : "Crawling Kingdom",
		"district" : "Yiva",
		"description" : "A small village town on the eastern coast of Yiva.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
		// Nothern Crawl
	
	"mogbalthur" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Mog Balthur",
		"region" : "Crawling Kingdom",
		"district" : "Nothern Crawl",
		"description" : "The fortress in the mountains, the youngest of the 3 Esmorzar Dwarven cities.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"yestir" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Yestir",
		"region" : "Crawling Kingdom",
		"district" : "Northern Crawl",
		"description" : "Sitting in the mountains in the Northern Peaks, a village.",
		"majorpop" : "",
		"features" : ["Cartographers Guild tower"],
		"vip" : [],
	},

	// Cape Drifting

	"cactir" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Cactir",
		"region" : "Cape Drifting",
		"district" : "",
		"description" : "In a snowy harbor in the Drifting Cape, Cactir a fishing town.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},

	// Endling
	
		// Brocking	

	"fallcrest" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Fallcrest",
		"region" : "Endling",
		"district" : "Brocking",
		"description" : "A village sitting in the intersection in Brocking. It sits on the Kings Road, connecting multiple regions.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"grogon" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Grogon",
		"region" : "Endling",
		"district" : "Brocking",
		"description" : "A village sitting on Brocking's Cape on the East.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"caediumforks" : {
		"id" : 8,
		"type" : "Keyloc",
		"coord" : [17.30869, -110.74219],
		"name" : "The Caedium Forks",
		"region" : "Endling",
		"district" : "Brocking",
		"description" : "",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
		// Godsend	
	
		// North End
	
		// Trevoy (The crossing)

	"brova" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Nebelheim",
		"region" : "Endling",
		"district" : "Trevoy 'The Crossing'",
		"description" : "",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
	// LEYLANDS
	
		// Dweiwar (eastern wilds)
	
	"increst" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Increst",
		"region" : "Leylands",
		"district" : "Dweiwar",
		"description" : "A northern outpost township",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"kanteen" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Kanteen",
		"region" : "Leylands",
		"district" : "Dweiwar",
		"description" : "",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
		// Kotia
	
	"rocton" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Rocton Outpost Village",
		"region" : "Leylands",
		"district" : "Kotia",
		"description" : "Serves as a bridging village connecting the regions together, it sits at an intersection on the Kings road.",
		"majorpop" : "",
		"features" : ["Adventurers Guild"],
		"vip" : [],
	},
	"illyasyl" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Illyasyl Outpost Village",
		"region" : "Leylands",
		"district" : "Kotia",
		"description" : "An elven outpost village that borders the Mweiwar Wilds. This village serves as guard to the elven cities within Mweiwar.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"maeimadtower" : {
		"id" : 8,
		"type" : "Keyloc",
		"coord" : [17.30869, -110.74219],
		"name" : "Maeimad Magicks Tower",
		"region" : "Leylands",
		"district" : "Kotia",
		"description" : "",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
		//Myeiwar Wilds
	
	"elheim" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Elheim",
		"region" : "Leylands",
		"district" : "Myeiwar Wilds",
		"description" : "One of the greater Elven townships in the Myeiwar Wilds, Elheim is known for its skilled hunters.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"nebelheim" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Nebelheim",
		"region" : "Leylands",
		"district" : "Myeiwar Wilds",
		"description" : "A greater Elven township in the Myeiwar Wilds.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	
	// SHATTERLANDS
	
		//Craggy
	
	"grenth" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Grenth",
		"region" : "Shatterlands",
		"district" : "Craggy",
		"description" : "The Harbor township of Grenth has become known for its bandits and piracy. It's become a popular cove for thieves and the like to come and sell stolen goods.",
		"majorpop" : "",
		"features" : ["Black Market"],
		"vip" : [],
	},
	"forendicastle" : {
		"id" : 8,
		"type" : "Keyloc",
		"coord" : [17.30869, -110.74219],
		"name" : "Forendi Castle",
		"region" : "Shatterlands",
		"district" : "Craggy",
		"description" : "",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
		
		//Karren
	
	"summerhall" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Summerhall",
		"region" : "Shatterlands",
		"district" : "Karren",
		"description" : "On the North-Eastern corner of the Scorchedwastes is a torn down desert village known as Summerhall. It used to be a fortress castletown, but has since just become a regular small town for traders and merchants.",
		"majorpop" : "",
		"features" : ["Summerhall Castle"],
		"vip" : [],
	},
		//Sharden
	
	"albanon" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Albanon",
		"region" : "Shatterlands",
		"district" : "Sharden",
		"description" : "A village on the southern shard islands",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
	"hureil" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Hureil",
		"region" : "Shatterlands",
		"district" : "Sharden",
		"description" : "The outpost township of turning is one of the major villages that acts as guards to the gates of Waverwen.",
		"majorpop" : "",
		"features" : [],
		"vip" : [],
	},
};