var cityinfo = {
	
	// MAJOR CITIES
	
	"croakenford" : {
		"id" : 0,
		"type" : "Major",
		"coord" : [-60.15244, 27.59766],
		"name" : "Croakenford",
		"region" : "Shatterlands",
		"district" : "Sharden",
		"description" : "The harbor city of Croakenford is maybe the most important city since it is the main port for exports and exports in Esmorzar.",
		"majorpop" : "Human, Diverse",
		"features" : ["Grand Harbor", "Trade export market"],
	},
	"eifelheim" : {
		"id" : 1,
		"type" : "Major",
		"coord" : [71.63599, 14.23828],
		"name" : "Eifelheim",
		"region" : "Leylands",
		"district" : "Mweiwar Wilds",
		"description" : "The central and capital Elven city in Esmorzar. Deep in to eh Mweiwar Wilds, it is a very defensible location protected by the surrounding Elfkin",
		"majorpop" : "Elven",
		"features" : [],
	},
	"faolin" : {
		"id" : 2,
		"type" : "Major",
		"coord" : [63.62674, -73.125],
		"name" : "Faolin",
		"region" : "Crawling Kingdom",
		"district" : "Northern Crawl",
		"description" : "The Northern Crawl is a mountainous area of Ezmorzar, and in a clearing lies Faolin, a city known for its farmland",
		"majorpop" : "Human, Dwarven, Diverse",
		"features" : [],
	},
	"tandent" : {
		"id" : 3,
		"type" : "Major",
		"coord" : [-33.28462, -125.50781],
		"name" : "Tandent",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The snout of Waverwen, Tandent is the capital of the Waverwen district. A large bustling city that maintains the whole regions trading and marketing.",
		"majorpop" : "",
		"features" : [],
	},
	"teitrasyl" : {
		"id" : 4,
		"type" : "Major",
		"coord" : [-12.72608, 92.98828],
		"name" : "Teitrasyl",
		"region" : "Endling",
		"district" : "Godsend",
		"description" : "The kingsland of Esmorzar, the home of the Pantheon, Teitrasyl holds some of the most historical and priceless monuments and features in Esmorzar.",
		"majorpop" : "",
		"features" : [],
	},
	"thragg" : {
		"id" : 5,
		"type" : "Major",
		"coord" : [-41.37681, -49.57031],
		"name" : "Thragg",
		"region" : "Shatterlands",
		"district" : "Craggy",
		"description" : "One of the 3 major Dwarven cities and sister city to Thrull, Thragg was a city made to exploit the great mineral harvests of the Craggy.",
		"majorpop" : "Dwarven",
		"features" : ["adssd"],
	},
	"thrull" : {
		"id" : 6,
		"type" : "Major",
		"coord" : [51.17934, 119.70703],
		"name" : "Thrull",
		"region" : "Cape Drifting",
		"district" : "",
		"description" : "The sister city of Thragg, Thrull relies on its cold coast for the harvest and export for sustaining trade prominence",
		"majorpop" : "Dwarven",
		"features" : [],
	},
	"waterhill" : {
		"id" : 7,
		"type" : "Major",
		"coord" : [47.39835, 51.67969],
		"name" : "Waterhill",
		"region" : "Endling",
		"district" : "Dweiwar",
		"description" : "An outpost village turned into a trade center, sitting at the crossroads between major cities it serves as a hub between them. It fills an identical job to Rocton, a smaller city. This village relies on farmland and lumber harvest for economy.",
		"majorpop" : "Elven, Dwarven, Diverse",
		"features" : [],
	},
	
	// Minor Cities & Features

	"turning" : {
		"id" : 8,
		"type" : "Minor",
		"coord" : [17.30869, -110.74219],
		"name" : "Turning Outpost Village",
		"region" : "Crawling Kingdom",
		"district" : "Waverwen",
		"description" : "The outpost township of turning is one of the major villages that acts as guards to the gates of Waverwen",
		"majorpop" : "",
		"features" : [],
	},
};